---
#apiVersion: apps/v1
#kind: Deployment
apiVersion: argoproj.io/v1alpha1 # Changed from apps/v1
kind: Rollout # Changed from Deployment
metadata:
  namespace: default
  name: helloworld
  labels:
    app: helloworld
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.helloworld: semver:~1.0
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      namespace: default
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: innovation009/helloworld-argocd:1.3
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: helloworld-svc
spec:
  ports:
  - port: 80
  selector:
    app: helloworld
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: demo.godevops.club
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: helloworld-svc
            port:
              number: 80
